# Generated by Django 5.1.7 on 2025-03-24 08:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0002_member_join_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['join_date'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='contributions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='current_address',
            field=models.TextField(default='Gambia'),
        ),
        
        
        migrations.AddField(
            model_name='member',
            name='new_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # migrations.AlterField(
        #    model_name='member',
        #    name='id',
        #    field=models.UUIDField(default=uuid.uuid4, editable=False, #primary_key=True, serialize=False),
        #),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
