# Generated by Django 5.1.7 on 2025-03-25 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0004_alter_member_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contributions',
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baduma_youths.member')),
            ],
        ),
    ]
