# Generated by Django 5.1.7 on 2025-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0005_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(max_length=200),
        ),
    ]
