# Generated by Django 5.1.7 on 2025-03-26 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0006_alter_member_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='description',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_address',
            field=models.TextField(verbose_name='Gambia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
