# Generated by Django 5.1.7 on 2025-03-26 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0007_remove_contribution_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
