# Generated by Django 5.1.7 on 2025-04-03 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0009_member_gender_member_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='new_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
