# Generated by Django 5.1.7 on 2025-04-05 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baduma_youths', '0011_community_rename_contribution_date_contribution_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='title',
            new_name='contribution_type',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='18', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='career',
            field=models.CharField(blank=True, default='civil servant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='educational_background',
            field=models.TextField(blank=True, default='High school', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='your_first_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='your_last_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='000  00 000 0000', max_length=20, null=True),
        ),
    ]
