# Generated by Django 5.2.5 on 2025-09-15 11:30

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('effective_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageFlexbox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255, verbose_name='Meeting Title')),
                ('date', models.DateTimeField(verbose_name='Meeting Date')),
                ('agenda', ckeditor.fields.RichTextField(blank=True, verbose_name='Agenda')),
                ('minutes', ckeditor.fields.RichTextField(blank=True, verbose_name='Minutes')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('image', models.ImageField(upload_to='meeting_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date', 'title'],
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=20)),
                ('career', models.CharField(blank=True, max_length=100)),
                ('educational_background', ckeditor.fields.RichTextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='project_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='project_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional. Leave blank for single-day events.', null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Full details of the event. Use the text editor to format content.')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('video_url', models.URLField(blank=True, help_text='Optional. A URL to a video on a platform like YouTube or Vimeo.')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='A promotional image for the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image', to=settings.FILER_IMAGE_MODEL)),
                ('video_file', filer.fields.file.FilerFileField(blank=True, help_text='Optional. Upload a video file directly (e.g., MP4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_video_file', to='filer.file')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='financial_reports/')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambianshk_youths.budget')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('category', models.CharField(choices=[('Operations', 'Operations'), ('Events', 'Events'), ('Administration', 'Administration'), ('Projects', 'Projects'), ('Other', 'Other')], max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
                ('incurred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gambianshk_youths.member')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('contribution_type', models.CharField(choices=[('Donation', 'Donation'), ('Membership Fee', 'Membership Fee'), ('Sponsorship', 'Sponsorship'), ('Monthly Contribution', 'Monthly Contribution'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambianshk_youths.member')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attendance_images/')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambianshk_youths.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambianshk_youths.member')),
            ],
            options={
                'unique_together': {('meeting', 'member')},
            },
        ),
    ]
