# Generated by Django 5.2 on 2025-09-20 12:12

import django.db.models.deletion
import django_ckeditor_5.fields
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('gambianshk_youths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='audio_file',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Optional. Upload an audio file (e.g., MP3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_audio_file', to='filer.file'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='constitution',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full details of the event. Use the text editor to format content.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='educational_background',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
